# Generated by Django 4.0.3 on 2022-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(help_text='Enter patient type here', max_length=4)),
                ('patient_path', models.FileField(help_text='Enter path to file location here', max_length=1000, upload_to='')),
                ('patient_number', models.IntegerField(help_text='Enter patient number here', max_length=4)),
            ],
        ),
    ]
