# Generated by Django 4.0.3 on 2022-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCA_app', '0002_alter_patientfiles_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfiles',
            name='patient_path',
            field=models.CharField(help_text='Enter path to file location here', max_length=1000),
        ),
    ]
